<?php

/* Author: Gianluca Giacometti */

$labels = array();
$labels['forward'] = 'Weiterleitung';
$labels['forwardforwards'] = 'Weiterleiten an (Addressen durch Kommata,\n Semikoli oder Umbrüche getrennt)';
$labels['forwardkeepcopies'] = 'Kopie der Original Nachricht behalten';

$messages = array();
$messages['forwardinvalidforwards'] = 'E-Mail Addresse ist nicht gültig';
$messages['forwardnovalidforwards'] = 'Keine gültige Addresse zur Weiterleitung';
$messages['forwardsuccessfullysaved'] = 'Weiterleiungen erfolgreich gespeichert';
$messages['forwarddriverconnecterror'] = 'Keine Verbindung zum Treiber';
$messages['forwarddriverprocesserror'] = 'Ausführungsfehler im Treiber';
$messages['forwardinternalerror'] = 'Lesefehler im Treiber';

?>
